@id=79faae40-ab7c-4688-88fc-b6774d293e5e

PUT http://127.0.0.1:5000/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Vs",
    "description": "Vas",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}